# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09811564baf7ff89251604969062cb5122cec8373e5ed162db957b082ce044a20ba1b67b18507d2cd0ad5e4f5668bb6ed60a3dff8829963f0cdfc78981f10ece

test:
  secret_key_base: e92bc2504c91d447dd951120e7df5468123803364281fdd00a22ac017b9524720fe5fc7be81c912451d5e02c751e7192403acfebeb42a755d412d170918b85d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
